# Generated by Django 3.1.3 on 2020-11-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='matches.team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='matches.team')),
            ],
        ),
    ]
