# Generated by Django 3.1.3 on 2020-11-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matchresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresults',
            name='goal_scored_team_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='matchresults',
            name='goal_scored_team_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
